### ISSUE TITLE
fix auto update for linux

### ISSUE THREAD

**Issue by Naoray** [Naoray/knote#15]
https://github.com/electron-userland/electron-builder/blob/docs/encapsulated%20manual%20update%20via%20menu.js

**Comment by Naoray** [comment]
[2021-09-15 21:54:54.118] [info]  Checking for update
[2021-09-15 21:54:55.005] [error] Error: Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://github.com/Naoray/knote/releases/latest), please ensure a production release exists: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:171181)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Object.t.newError (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:8062)
    at t.GitHubProvider.getLatestVersionString (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:183093)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async t.GitHubProvider.getLatestVersion (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:181635)
    at async f.getUpdateInfoAndProvider (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:74182)
    at async f.doCheckForUpdates (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:74468),
XML:
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:https://github.com/Naoray/knote/releases</id>
  <link type="text/html" rel="alternate" href="https://github.com/Naoray/knote/releases"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/Naoray/knote/releases.atom"/>
  <title>Release notes from knote</title>
  <updated>2021-09-15T19:37:13Z</updated>
  <entry>
    <id>tag:github.com,2008:Repository/392605975/v0.1.5</id>
    <updated>2021-09-15T19:37:13Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/Naoray/knote/releases/tag/v0.1.5"/>
    <title>v0.1.5</title>
    <content type="html">&lt;p&gt;v0.1.5&lt;/p&gt;</content>
    <author>
      <name>Naoray</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/10154100?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/392605975/v0.1.4</id>
    <updated>2021-09-15T19:26:52Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/Naoray/knote/releases/tag/v0.1.4"/>
    <title>0.1.4</title>
    <content type="html">&lt;p&gt;&lt;strong&gt;Fix&lt;/strong&gt;&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;auto update for linux version&lt;/li&gt;
&lt;/ul&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/392605975/v0.1.3</id>
    <updated>2021-09-15T19:13:51Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/Naoray/knote/releases/tag/v0.1.3"/>
    <title>v0.1.3</title>
    <content type="html">&lt;p&gt;v0.1.3&lt;/p&gt;</content>
    <author>
      <name>Naoray</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/10154100?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/392605975/v0.1.2</id>
    <updated>2021-09-15T13:41:39Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/Naoray/knote/releases/tag/v0.1.2"/>
    <title>0.1.2</title>
    <content type="html">&lt;p&gt;&lt;strong&gt;Changed&lt;/strong&gt;&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;markdown strikethrough &lt;code&gt;~~strikethrough~~&lt;/code&gt; and table synthax are now rendering correctly&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;&lt;strong&gt;Fixes&lt;/strong&gt;&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;show rendered Markdown not reacting in some cases&lt;/li&gt;
&lt;li&gt;initial markdown render not showing up&lt;/li&gt;
&lt;li&gt;project opening without existing note caused an exception&lt;/li&gt;
&lt;/ul&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/392605975/v0.1.1</id>
    <updated>2021-09-15T13:26:32Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/Naoray/knote/releases/tag/v0.1.1"/>
    <title>v0.1.1</title>
    <content type="html">&lt;p&gt;wip&lt;/p&gt;</content>
    <author>
      <name>Naoray</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/10154100?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/392605975/v0.1.0</id>
    <updated>2021-09-13T12:51:24Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/Naoray/knote/releases/tag/v0.1.0"/>
    <title>0.1.0</title>
    <content type="html">&lt;p&gt;Initial Version&lt;/p&gt;</content>
    <author>
      <name>Naoray</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/10154100?s=60&amp;v=4"/>
  </entry>
</feed>

    at Object.t.newError (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:8062)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:181794)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async f.getUpdateInfoAndProvider (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:74182)
    at async f.doCheckForUpdates (/tmp/.mount_knote-DmnNOp/resources/app.asar/background.js:2:74468)
